# Superarch managed bash configuration

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Prompt
if command -v starship > /dev/null 2>&1; then
  export STARSHIP_CONFIG="$HOME/.config/current/starship.toml"
  eval "$(starship init bash)"
else
  PS1='[\u@\h \W]\$ '
fi

# SSH key management
eval $(keychain --eval --quiet id_ed25519)

# Dircolors
[ -f ~/.config/current/dircolors ] && eval "$(dircolors ~/.config/current/dircolors)"

# Mason
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

# Mise
eval "$(mise activate bash)"
